export { deactivate } from './deactivate'
export { inspect } from './inspect'
export { proof } from './proof'
export { txDeactivate } from './txDeactivate'
export { txProof } from './txProof'
export { txResult } from './txResult'
export { txStopVoting } from './txStopVoting'
