name: Publish to npm

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for npm provenance

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        continue-on-error: true  # Don't fail if tests fail (adjust as needed)

      - name: Build
        run: npm run build

      - name: Determine npm tag
        id: npm-tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if [[ "$VERSION" == *"beta"* ]]; then
            echo "tag=beta" >> $GITHUB_OUTPUT
          elif [[ "$VERSION" == *"alpha"* ]]; then
            echo "tag=alpha" >> $GITHUB_OUTPUT
          elif [[ "$VERSION" == *"rc"* ]]; then
            echo "tag=rc" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Publish to npm
        run: npm publish --tag ${{ steps.npm-tag.outputs.tag }} --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release (if not exists)
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          body: |
            ## Installation

            ```bash
            npm install -g @dorafactory/maci-operator@${{ steps.npm-tag.outputs.version }}
            ```

            Or with specific tag:

            ```bash
            npm install -g @dorafactory/maci-operator@${{ steps.npm-tag.outputs.tag }}
            ```

            ## Docker

            ```bash
            docker pull ghcr.io/dorafactory/amaci-operator:${{ steps.npm-tag.outputs.tag }}
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
